source 'https://rubygems.org'

group :development do
  gem 'berkshelf', '~> 4.0'
  gem 'kitchen-openstack', '~> 1.8'
  gem 'bundler',  '~> 1.10'
  gem 'rake',     '~> 10.0'
  gem 'rspec',    '~> 3.3'
  gem 'rubocop',  '~> 0.33.0'
  gem 'foodcritic', '~> 5.0'
  gem 'chefspec', '~> 4.2'
end

# Uncomment these lines if you want to live on the Edge:
#
# group :development do
#   gem "berkshelf", github: "berkshelf/berkshelf"
#   gem "vagrant", github: "mitchellh/vagrant", tag: "v1.6.3"
# end
#
# group :plugins do
#   gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
#   gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
# end

# gem "test-kitchen"
# gem "kitchen-vagrant"
